"""Generates synthetic human/bot behavior data and trains the DeepCheck models.

Run this before starting the backend:
    python train_model.py

Produces:
    model.pkl      -- joblib bundle: {scaler, rf, iso_forest, feature_names,
                      neutral_defaults}. The RandomForest is the served score.
    lstm_model.pt  -- only with TRAIN_LSTM=1. Kept trainable so its removal
                      from the score can be re-measured; see scorer.py.

Training data is generated by simulating *raw* behavioral sessions (mouse
trajectories, click timings, scroll events, keydown timestamps) for human and
bot personas, then running them through the same `scorer.extract_features()`
used at inference time -- not by hand-picking numbers directly in [0, 1] for
each feature. This closes the gap that caused ivme_degisimi to previously be
generated in a completely different numeric range than what the real
extraction formula could ever produce (see scorer.py's
ACCELERATION_VARIANCE_DIVISOR comment). Any future change to a feature
formula automatically flows into training data too, since both paths run the
same code.
"""

import json
import math
import os
import sys

import joblib
import numpy as np
import torch
import torch.nn as nn
import sklearn
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import scorer
from lstm_model import FEATURE_NAMES, SEQUENCE_LENGTH, BehaviorLSTM
from scorer import extract_features

# Sessions, not rows: each one yields SEQUENCE_LENGTH flush windows, so this
# is 250,000 extracted feature windows -- five times the old dataset -- of
# which the 25,000 final windows train the tabular models and all 250,000
# train the sequence model. Sized so a cold `docker-compose up` finishes
# training in a few minutes rather than ten.
# Overridable so CI can train a small model quickly. The default is what
# ships; anything smaller is for a smoke test, not for a real model.
N_SESSIONS = int(os.getenv("N_SESSIONS", "25000"))
HESITATION_THRESHOLD_MS = 400  # must match sdk/deepcheck.js's HESITATION_THRESHOLD_MS

# Mirrors sdk/deepcheck.js's default flush interval. One simulated session is
# SEQUENCE_LENGTH consecutive flushes, i.e. the same ~20 seconds of behavior
# the LSTM reads back out of Postgres at serving time. Before this, a
# "sequence" was ten jittered copies of a single instant, so the temporal
# model was fed no time information at all while carrying 30% of the
# ensemble weight.
FLUSH_INTERVAL_MS = 2000

# Fraction of each class simulated as the "other" persona -- sophisticated
# bots that mimic human timing (bot_sophisticated), and rushed/efficient
# humans that look more robotic (human_rushed). Without this, the two classes
# would be cleanly separable, which is a modeling smell, not a real result.
CONTAMINATION_RATE = 0.10

# Fraction of each class whose behavior CHANGES mid-session: human then
# robotic (labelled bot -- a session handed off to automation) and robotic
# then human (labelled human -- a script that warms up a page a real customer
# then uses). These are the samples that carry temporal information; without
# them the sequence model has nothing to learn that the aggregate row does
# not already say.
DRIFT_RATE = 0.12

SEED = 42
rng = np.random.default_rng(SEED)

# The LSTM is no longer part of the score (the measurement is in scorer.py's
# compute_risk), so a cold `docker-compose up` does not pay to train it. Set
# TRAIN_LSTM=1 to write lstm_model.pt for re-measurement against real data.
TRAIN_LSTM = os.getenv("TRAIN_LSTM", "0").strip() == "1"

# The forests take random_state=42, but NOTHING seeded torch. The LSTM's weight
# initialisation, its dropout masks and the batch shuffling below all drew from
# torch's global RNG, so every run of this script produced a different sequence
# model -- one carrying 30% of the ensemble weight. Two runs of "the same"
# pipeline disagreed by more than ten risk points on the same session, and the
# claim that the artifacts are reproducible from a fixed seed was true only of
# the forests. Retraining could therefore turn a detected bot into a merely
# "suspicious" one with no code change at all, which is precisely the kind of
# result nobody can defend.
torch.manual_seed(SEED)


def _hesitation_intervals(event_times: list[int], flush_checkpoint: int | None = None) -> list[int]:
    """Mirrors sdk/deepcheck.js's recordHesitation() + its flush-time idle
    check: gaps >= threshold between consecutive tracked events count, AND
    if the flush happens while the session has gone quiet since the last
    event, that trailing silence counts too. Without the trailing check, a
    burst of activity followed by pure idle time until the window closes was
    invisible to hesitation tracking on both the SDK and training-data
    sides -- fixing only one would reintroduce a train/serve mismatch."""
    ts = sorted(event_times)
    gaps = [b - a for a, b in zip(ts, ts[1:]) if (b - a) >= HESITATION_THRESHOLD_MS]
    if flush_checkpoint is not None and ts:
        trailing_gap = flush_checkpoint - ts[-1]
        if trailing_gap >= HESITATION_THRESHOLD_MS:
            gaps.append(trailing_gap)
    return gaps


class _Stream:
    """Mutable per-session generation state.

    One cursor (`t`) drives the sequential phases -- move the mouse, click,
    type, pause -- because that ordering is what produces natural hesitation
    gaps in the merged event stream. Running every channel in parallel
    instead would fill the timeline with keystrokes and erase the pauses
    entirely, collapsing tereddut_skoru toward zero for humans.
    """

    def __init__(self, base_t: int):
        self.t = base_t
        self.x = 200.0
        self.y = 200.0
        self.scroll_y = 0
        self.mouse: list[dict] = []
        self.clicks: list[dict] = []
        self.scrolls: list[dict] = []
        self.keys: list[dict] = []
        self.focus: list[float] = []
        self.times: list[int] = []

    def mouse_event(self, x: float, y: float, t: int) -> None:
        self.mouse.append({"x": x, "y": y, "t": t})
        self.times.append(t)

    def click_event(self, x: float, y: float, t: int) -> None:
        self.clicks.append({"x": x, "y": y, "t": t})
        self.times.append(t)

    def scroll_event(self, scroll_y: float, t: int) -> None:
        self.scrolls.append({"scrollY": scroll_y, "t": t})
        self.times.append(t)

    def key_event(self, t: int) -> None:
        self.keys.append({"t": t})
        self.times.append(t)


# --- Synthetic identities ------------------------------------------------------
#
# Used ONLY by backend/profile_lab.py, which measures the per-customer
# behavioural profile (profiles.py). Nothing in training calls any of this, and
# it must stay that way: see _session_traits() below.
#
# Without an identity the generator draws every trait i.i.d. per session, so
# the variance WITHIN one "customer" equals the variance BETWEEN customers and a
# deviation-from-your-own-past statistic measured on it is an artefact of the
# generator, not evidence of anything.
#
# An identity's traits persist across its sessions; a session's traits are the
# identity's plus per-session noise. The RATIO below is an ASSUMPTION, not a
# measurement: nobody has measured how much one person's behaviour varies between
# their own sessions, because that needs real customers. It is declared here so a
# reader can see which number the results depend on.
WITHIN_IDENTITY_SD_RATIO = 0.6

# The "human" persona's persistent parameters, as
#   name: (population centre, between-identity SD, lower clip, upper clip).
# Each centre is EXACTLY the constant _phase_human uses when no identity is
# given, so an identity is a person drawn around today's persona rather than a
# new persona. The between-identity SDs are assumptions of the same kind as the
# ratio above -- plausible spreads, not measured ones -- and they set how far
# apart two synthetic people are, which is what every impostor number in
# docs/profile-evaluation.md depends on.
IDENTITY_PARAMETERS = {
    # Pointer step size and its jitter (px per sample): rng.normal(6, 6), (4, 5).
    "step_x_mean": (6.0, 2.0, 0.5, 15.0),
    "step_x_sd": (6.0, 2.0, 1.0, 15.0),
    "step_y_mean": (4.0, 1.5, 0.5, 10.0),
    "step_y_sd": (5.0, 1.5, 1.0, 12.0),
    # Centre of the pointer sampling interval, uniform(50, 150) today (+-50 ms).
    "move_dt_centre": (100.0, 25.0, 60.0, 200.0),
    # How often a movement is interrupted by a pause.
    "move_pause_prob": (0.05, 0.02, 0.0, 0.2),
    # Centre of the pause before a click, uniform(300, 900) today (+-300 ms).
    "click_pause_centre": (600.0, 150.0, 350.0, 1200.0),
    # Typing rhythm: lognormal(mean=5.0, sigma=0.5) today.
    "key_log_mean": (5.0, 0.3, 4.0, 6.0),
    "key_log_sigma": (0.5, 0.12, 0.2, 0.9),
    # Propensities to scroll and to leave the tab in a window.
    "scroll_prob": (0.35, 0.15, 0.0, 0.9),
    "focus_prob": (0.15, 0.07, 0.0, 0.5),
}

# The input modalities a synthetic identity can be simulated in. Touch is NOT
# one of them: this simulator has no model of a finger (no hover before a tap,
# gesture-driven scrolling, pointermove only until the browser takes the gesture
# over), and the served model has never seen a touch trajectory either. A touch
# profile number produced here would be a number about an invented persona.
IDENTITY_MODALITIES = ("mouse", "keyboard")


def _identity_traits() -> dict:
    """One synthetic person: a draw of every IDENTITY_PARAMETERS entry."""
    return {
        name: float(np.clip(rng.normal(centre, between_sd), lo, hi))
        for name, (centre, between_sd, lo, hi) in IDENTITY_PARAMETERS.items()
    }


def _between(traits: dict, name: str, lo: float, hi: float) -> tuple[float, float]:
    """The (lo, hi) of a uniform draw: today's literal bounds when the traits
    carry no identity, otherwise the same width around the identity's centre."""
    if name not in traits:
        return lo, hi
    half = (hi - lo) / 2.0
    return traits[name] - half, traits[name] + half


def _session_traits(identity: dict | None = None) -> dict:
    """Traits decided once for the whole session rather than per phase.

    A keyboard-only user does not click in one phase and start clicking in
    the next; a headless script does not grow a mouse halfway through. These
    have to be session-level, or the personas blur together across a 20s
    session in a way a single 10s window never exposed.

    HARD CONSTRAINT: called with no identity -- which is every call training
    makes -- this consumes exactly the rng draws, in exactly the order, and
    returns exactly the dict it did before identities existed, and the phase
    functions read no identity key they are not given. So
    generate_synthetic_dataset() is bit-identical and the served model does not
    change. test_profiles.py (T30) pins it.

    With an identity, the five draws above still happen first (so a bot and a
    person consume the stream the same way), and the identity's parameters are
    added AFTER them, each with its own per-session noise.
    """
    traits = {
        # Sometimes zero clicks for the entire session: a script that calls
        # form.submit(), or a real human navigating by Tab only. Without this,
        # tiklama_yogunlugu == 0.0 would never appear in training for any
        # persona, so the model would have to extrapolate that value.
        "zero_clicks": bool(rng.random() < 0.15),
        # Real users often fill a form almost entirely by typing, with little
        # or no mouse movement. Without human examples of sparse mouse data,
        # the model only ever sees that pattern from headless bots and learns
        # "no mouse data" as an almost-deterministic bot signature.
        "sparse_mouse": bool(rng.random() < 0.30),
        # Headless (no mouse/scroll dispatch at all) vs scripted-with-motion
        # (Selenium/Puppeteer-style synthetic mousemove and scroll).
        "headless": bool(rng.random() < 0.5),
        # bot_sophisticated's near-constant velocity, fixed per session.
        "vx": float(rng.uniform(2, 5)),
        "vy": float(rng.uniform(1, 3)),
    }
    if identity is None:
        return traits
    for name, (_, between_sd, lo, hi) in IDENTITY_PARAMETERS.items():
        noise = rng.normal(0.0, WITHIN_IDENTITY_SD_RATIO * between_sd)
        traits[name] = float(np.clip(identity[name] + noise, lo, hi))
    return traits


def _phase_human(s: _Stream, traits: dict) -> None:
    # Every traits.get() default below is the literal this persona used before
    # identities existed, so a training session (no identity keys) makes the
    # identical draws. Only an identity session supplies the keys.
    if traits.get("no_pointer"):
        n_points = 0
    else:
        n_points = int(rng.integers(0, 3)) if traits["sparse_mouse"] else int(rng.integers(10, 40))
    dt_lo, dt_hi = _between(traits, "move_dt_centre", 50, 150)
    for _ in range(n_points):
        s.x += rng.normal(traits.get("step_x_mean", 6), traits.get("step_x_sd", 6))
        s.y += rng.normal(traits.get("step_y_mean", 4), traits.get("step_y_sd", 5))
        s.t += int(rng.uniform(dt_lo, dt_hi))
        s.mouse_event(s.x, s.y, s.t)
        if rng.random() < traits.get("move_pause_prob", 0.05):  # natural pause while moving the mouse
            s.t += int(rng.uniform(400, 1200))

    n_clicks = 0 if traits["zero_clicks"] else int(rng.integers(1, 5))
    click_lo, click_hi = _between(traits, "click_pause_centre", 300, 900)
    for _ in range(n_clicks):
        s.t += int(rng.uniform(click_lo, click_hi))  # natural pause before clicking
        s.click_event(s.x, s.y, s.t)

    n_keys = int(rng.integers(15, 50))
    for _ in range(n_keys):
        # ~100-350ms, occasional longer pause
        s.t += int(rng.lognormal(mean=traits.get("key_log_mean", 5.0), sigma=traits.get("key_log_sigma", 0.5)))
        s.key_event(s.t)

    if rng.random() < traits.get("scroll_prob", 0.35):
        for _ in range(int(rng.integers(2, 6))):
            s.scroll_y += int(rng.uniform(40, 150))
            s.t += int(rng.uniform(60, 180))
            s.scroll_event(s.scroll_y, s.t)

    if rng.random() < traits.get("focus_prob", 0.15):
        s.focus.append(s.t + int(rng.uniform(500, 3000)))


def _phase_human_rushed(s: _Stream, traits: dict) -> None:
    # NOTE: with tighter dt (faster movement) but similar jitter magnitude to
    # "human", this persona's acceleration variance came out HIGHER than plain
    # "human" (median hit the 1.0 clip ceiling) when first tuned -- dt shrinks
    # the denominator twice (speed, then acceleration), amplifying rather than
    # smoothing. Slightly wider dt and slightly smaller jitter brings it to a
    # believable "efficient but still human" range.
    n_points = int(rng.integers(0, 3)) if traits["sparse_mouse"] else int(rng.integers(6, 15))
    for _ in range(n_points):
        s.x += rng.normal(6, 4)
        s.y += rng.normal(4, 3)
        s.t += int(rng.uniform(60, 120))
        s.mouse_event(s.x, s.y, s.t)

    # NOTE: this used to be uniform(150, 400) -- numpy's upper bound is
    # exclusive, so it could NEVER reach HESITATION_THRESHOLD_MS (400),
    # meaning 100% of human_rushed samples got hesitation_intervals=[].
    # Widened so some click gaps naturally cross the threshold, like a real
    # (just efficient) human would.
    n_clicks = 0 if traits["zero_clicks"] else int(rng.integers(1, 5))
    for _ in range(n_clicks):
        s.t += int(rng.uniform(150, 650))
        s.click_event(s.x, s.y, s.t)

    n_keys = int(rng.integers(10, 35))
    for _ in range(n_keys):
        s.t += int(rng.uniform(60, 150))
        s.key_event(s.t)

    if rng.random() < 0.15:
        s.t += int(rng.uniform(50, 200))
        s.scroll_y += int(rng.uniform(50, 300))
        s.scroll_event(s.scroll_y, s.t)


def _phase_bot(s: _Stream, traits: dict) -> None:
    headless = traits["headless"]

    if traits["zero_clicks"]:
        n_clicks = 0
    else:
        n_clicks = int(rng.integers(1, 3)) if headless else int(rng.integers(4, 10))
    for _ in range(n_clicks):
        s.click_event(300.0, 200.0, s.t)
        s.t += int(rng.integers(1, 5)) if headless else max(150 + int(rng.normal(0, 8)), 1)

    # Real automation is not always perfectly instant end to end: page loads,
    # API round trips, explicit sleep()s between scripted steps, or basic
    # rate-limit evasion delays are common. Without this, EVERY bot sample has
    # hesitation_intervals=[], which trains the model to treat "hesitation
    # exactly at the neutral fallback" as an almost-perfect bot fingerprint --
    # a single incidental pause at inference then flips the whole verdict.
    if rng.random() < 0.30:
        s.t += int(rng.uniform(400, 1100))

    n_keys = int(rng.integers(0, 20))
    for _ in range(n_keys):
        s.key_event(s.t)
        s.t += int(rng.integers(1, 5)) if headless else max(3 + int(rng.normal(0, 1)), 1)


def _phase_bot_sophisticated(s: _Stream, traits: dict) -> None:
    n_points = int(rng.integers(15, 30))
    for _ in range(n_points):
        # More jitter than the plain "bot" variant -- this persona is the
        # hard-to-detect, human-mimicking bot, so its acceleration profile
        # should land closer to human territory.
        s.x += traits["vx"] * 10 + rng.normal(0, 2.5)
        s.y += traits["vy"] * 10 + rng.normal(0, 1.8)
        s.t += max(80 + int(rng.normal(0, 7)), 1)  # mostly regular interval
        s.mouse_event(s.x, s.y, s.t)

    # Same rationale as the "bot" branch: an occasional realistic pause
    # between phases, so hesitation_intervals==[] cannot be a near-guaranteed
    # bot fingerprint.
    if rng.random() < 0.30:
        s.t += int(rng.uniform(400, 1100))

    n_clicks = 0 if traits["zero_clicks"] else int(rng.integers(2, 4))
    for _ in range(n_clicks):
        s.t += max(500 + int(rng.normal(0, 15)), 1)  # mostly evenly spaced
        s.click_event(s.x, s.y, s.t)

    n_keys = int(rng.integers(10, 30))
    for _ in range(n_keys):
        s.t += max(150 + int(rng.normal(0, 8)), 1)  # mostly too-regular typing interval
        s.key_event(s.t)


_PHASES = {
    "human": _phase_human,
    "human_rushed": _phase_human_rushed,
    "bot": _phase_bot,
    "bot_sophisticated": _phase_bot_sophisticated,
}


def _background_motion(s: _Stream, traits: dict, base_t: int) -> None:
    """The plain "bot" persona's synthetic mousemove and scroll.

    These run on their own cursors, in parallel with the click and key phase,
    because that is how a Selenium-style script actually behaves: the driver
    dispatches motion events while the scripted steps proceed. Small jitter
    rather than a mathematically perfect constant -- real scripted dispatch
    still carries OS and rendering timing noise, and an exact-zero variance
    would hand the model a single-feature fingerprint.
    """
    if traits["headless"]:
        return

    n_points = int(rng.integers(10, 20))
    x, y = 100.0, 100.0
    t = base_t
    for _ in range(n_points):
        x += 5.0 + rng.normal(0, 3.0)
        y += 2.0 + rng.normal(0, 2.2)
        t += max(80 + int(rng.normal(0, 10)), 1)
        s.mouse_event(x, y, t)

    n_scroll = int(rng.integers(4, 8))
    t = base_t
    for i in range(1, n_scroll + 1):
        t += max(90 + int(rng.normal(0, 6)), 1)
        s.scroll_event(50.0 * i, t)


def _simulate_window(persona: str, traits: dict, base_t: int) -> dict:
    """One flush payload: exactly what the SDK would POST at one tick.

    This is the unit the model is served, so it is the unit the model is
    trained on. Its content and its statistics are unchanged from when a
    training row was a single window -- what changed is that a session is now
    a *sequence* of these rather than one in isolation.
    """
    s = _Stream(base_t)
    _PHASES[persona](s, traits)

    if persona == "bot":
        _background_motion(s, traits, base_t)

    # Simulate the flush boundary itself: activity is often followed by real
    # idle time before the window closes (e.g. a fast burst of typing, then
    # nothing until the next flush fires). See _hesitation_intervals().
    flush_checkpoint = s.t
    if rng.random() < 0.40:
        flush_checkpoint = s.t + int(rng.uniform(400, 2000))

    return {
        "mouse_trajectory": s.mouse,
        "click_timing": s.clicks,
        "scroll_events": s.scrolls,
        "hesitation_intervals": _hesitation_intervals(s.times, flush_checkpoint),
        "focus_changes": s.focus,
        "key_events": s.keys,
    }


def _persona_at_step(persona: str, step: int) -> str:
    """Which persona is driving the session at flush `step`.

    A drift session behaves as one persona for its first half and another for
    its second. That change is the only thing in the training set a sequence
    model can learn and an aggregate row cannot represent, so it is what makes
    feeding the LSTM real history worth doing at all.
    """
    if persona == "drift_to_bot":
        return "human" if step < SEQUENCE_LENGTH // 2 else "bot_sophisticated"
    if persona == "drift_to_human":
        return "bot_sophisticated" if step < SEQUENCE_LENGTH // 2 else "human"
    return persona


def simulate_session_windows(persona: str, base_t: int) -> list[dict]:
    """A whole session as SEQUENCE_LENGTH consecutive flush payloads.

    Session-level traits (keyboard-only, sparse mouse, headless) are drawn
    once and held for every window: a real user does not stop being
    keyboard-only halfway through, and a headless script does not grow a
    mouse. That is what makes the ten windows a coherent session rather than
    ten unrelated samples.

    Known approximation: consecutive windows are drawn independently, while
    the real SDK ships a 10s ROLLING window every 2s, so two real consecutive
    flushes share most of their events and are far more correlated than two
    windows here. The marginal distribution of any single window is exactly
    the one the tabular models are calibrated on, which is the property worth
    protecting; the cost is that the LSTM sees noisier step-to-step variation
    in training than in production.
    """
    traits = _session_traits()
    return [
        _simulate_window(_persona_at_step(persona, step), traits, base_t + step * FLUSH_INTERVAL_MS)
        for step in range(SEQUENCE_LENGTH)
    ]


def simulate_identity_sessions(identity: dict, n_sessions: int, modality: str) -> list[list[dict]]:
    """n_sessions separate sessions by ONE synthetic person, each SEQUENCE_LENGTH
    flush payloads long -- the same unit /api/decision reads back out of
    behavior_data (its last main.SPRT_MAX_FLUSHES == 10 flushes).

    Always the "human" persona: a returning customer. The identity sets the
    persona's persistent parameters; each session adds its own noise
    (WITHIN_IDENTITY_SD_RATIO), and every window inside a session still carries
    the persona's ordinary per-event randomness.

    `modality` pins what the SDK would report as the pointer mix:
      mouse     -- a pointer trajectory in every window and at least one click
                   (a checkout is confirmed by clicking), never "sparse";
      keyboard  -- no pointer event at all and no click: Tab and Enter only.
    Touch is refused, not approximated; see IDENTITY_MODALITIES.

    Not used by training. Draws from the module rng like everything else here,
    so a caller that wants reproducible identities reseeds `rng` first
    (profile_lab.py does).
    """
    if modality not in IDENTITY_MODALITIES:
        raise ValueError(
            f"desteklenmeyen giris turu {modality!r}: simulator yalnizca "
            f"{', '.join(IDENTITY_MODALITIES)} uretir (dokunmatik modeli yok)"
        )
    sessions = []
    for _ in range(n_sessions):
        traits = _session_traits(identity)
        if modality == "keyboard":
            traits["no_pointer"] = True
            traits["zero_clicks"] = True
        else:
            traits["sparse_mouse"] = False
            traits["zero_clicks"] = False
        base_t = 1_700_000_000_000 + int(rng.integers(0, 10**9))
        sessions.append(
            [_simulate_window("human", traits, base_t + step * FLUSH_INTERVAL_MS) for step in range(SEQUENCE_LENGTH)]
        )
    return sessions


def _pick_persona(is_bot: int) -> str:
    if is_bot:
        if rng.random() < DRIFT_RATE:
            return "drift_to_bot"
        return "bot_sophisticated" if rng.random() < CONTAMINATION_RATE else "bot"
    if rng.random() < DRIFT_RATE:
        return "drift_to_human"
    return "human_rushed" if rng.random() < CONTAMINATION_RATE else "human"


def generate_synthetic_dataset(n_rows: int = N_SESSIONS):
    """Returns (X, sequences, y).

    X          -- the FINAL flush's features per session, the aggregate row
                  RandomForest and IsolationForest train on.
    sequences  -- all SEQUENCE_LENGTH flushes per session, the real time
                  series the LSTM trains on. Its last timestep is X's row.
    """
    is_bot = rng.integers(0, 2, size=n_rows)
    n_features = len(FEATURE_NAMES)
    X = np.empty((n_rows, n_features))
    sequences = np.empty((n_rows, SEQUENCE_LENGTH, n_features))

    for i in range(n_rows):
        base_t = 1_700_000_000_000 + int(rng.integers(0, 10**9))
        for step, payload in enumerate(simulate_session_windows(_pick_persona(is_bot[i]), base_t)):
            features = extract_features(payload)
            sequences[i, step] = [features[name] for name in FEATURE_NAMES]
        X[i] = sequences[i, -1]

    return X, sequences, is_bot


# Sessions used to find the neutral fallbacks before the real dataset is
# generated. Small on purpose: this only needs to locate the human/bot
# midpoint, not to train anything.
PILOT_SESSIONS = int(os.getenv("PILOT_SESSIONS", "2500"))
PILOT_PASSES = 2


# Sessions used to measure the raw distribution of each log-scaled feature.
SCALING_SESSIONS = int(os.getenv("SCALING_SESSIONS", "1500"))


# Overridable, because the default only holds when lab/ sits next to backend/.
# In the container backend/ is mounted at /app, so the default resolves to /lab
# -- which is why docker-compose mounts ./lab there. Without that mount the
# container trained on synthetic data ONLY, said so in one line, and served a
# model the published evaluation numbers did not describe.
REAL_TELEMETRY_PATH = os.getenv(
    "REAL_TELEMETRY_PATH",
    os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "lab", "real_telemetry.json"
    ),
)

# Real rows are vastly outnumbered by synthetic ones, so without a weight they
# would be rounding error. This makes the real set count for roughly as much in
# aggregate as the synthetic set, while keeping synthetic coverage of the
# personas the browser lab does not enumerate.
REAL_TELEMETRY_WEIGHT = 120.0

# Fraction of real RUNS -- not flushes -- held out for evaluation. Splitting by
# run matters: every flush from one browser session is correlated with its
# siblings, so a random per-flush split puts the same session on both sides and
# reports a number that will not reproduce on a fresh session.
REAL_HOLDOUT_FRACTION = 0.3


# The channels scorer.extract_raw() reads from one flush, under the names the
# SDK posts them. A real sample that carries these is re-extracted every time
# it is loaded rather than trusted as stored.
RAW_CHANNELS = (
    "mouse_trajectory",
    "click_timing",
    "scroll_events",
    "hesitation_intervals",
    "focus_changes",
    "key_events",
)

# Channels whose events carry a timestamp. A flush with none of them (only
# hesitation intervals: an idle tab) is answered by /api/analyze without being
# stored or scored, so a row made of one describes nothing the served model is
# ever asked about.
TIMESTAMPED_CHANNELS = (
    "mouse_trajectory",
    "click_timing",
    "scroll_events",
    "key_events",
    "focus_changes",
)

# Scaling endpoints and neutral fallbacks are rounded to three decimals when
# computed, so any difference beyond float noise is a different coordinate
# system, not the same one printed twice.
_STAMP_TOLERANCE = 1e-6


def _sample_raw(sample: dict) -> dict | None:
    raw = sample.get("raw")
    if not isinstance(raw, dict):
        return None
    return {name: raw.get(name) or [] for name in RAW_CHANNELS}


def _carries_behaviour(raw: dict) -> bool:
    return any(raw.get(name) for name in TIMESTAMPED_CHANNELS)


def _group_of(sample: dict) -> str:
    """The unit of the holdout split.

    PERSON where one is recorded, falling back to the session and then to the
    scenario. The unit has to be whoever generated the data: flushes within a
    sitting are correlated, and sittings by the same person are correlated
    too. Split by session alone and one person who contributed ten sittings
    lands on both sides, so the reported number answers "does it recognise
    this person again" instead of "does it work on somebody new" -- and only
    the second question justifies collecting the data at all.
    record_session.py --person fills this in.
    """
    return sample.get("person_id") or sample.get("run_id") or sample["scenario"]


def _session_key(sample: dict) -> str:
    """One server session: the unit smooth_session_score() folds over.

    Usually the run. A lab run whose token expired part-way re-registers, and
    the server starts a new session -- and new smoothing -- from that flush,
    which capture.py records as session_index.
    """
    base = sample.get("run_id") or sample["scenario"]
    part = int(sample.get("session_index") or 0)
    return base if part == 0 else f"{base}~{part}"


def _read_real_payload(path: str) -> dict | None:
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        payload = json.load(fh)
    return payload if payload.get("samples") else None


def _structural_split(samples: list[dict]) -> tuple[list[dict], set, int, int]:
    """Rows that can be blended at all, and which groups are held out.

    Decided WITHOUT looking at the scaling in force, so the split cannot move
    when a retrain changes the scale: compute_feature_scaling() must know which
    rows are training-side before any scale exists. Returns (usable, holdout
    groups, rows too old for the feature set, idle rows).
    """
    usable, incomplete, idle = [], 0, 0
    for sample in samples:
        raw = _sample_raw(sample)
        if raw is not None:
            if _carries_behaviour(raw):
                usable.append(sample)
            else:
                idle += 1
            continue
        # A capture taken before a feature was added cannot be blended: the
        # vector would be the wrong width, or worse, silently mis-ordered.
        features = sample.get("features") or {}
        if all(features.get(name) is not None for name in FEATURE_NAMES):
            usable.append(sample)
        else:
            incomplete += 1

    groups = sorted({_group_of(s) for s in usable})
    holdout_rng = np.random.default_rng(1234)
    holdout_rng.shuffle(groups)
    holdout = set(groups[: max(1, int(len(groups) * REAL_HOLDOUT_FRACTION))]) if groups else set()
    return usable, holdout, incomplete, idle


def _close(recorded, current: list[float]) -> bool:
    values = recorded if isinstance(recorded, (list, tuple)) else [recorded]
    try:
        values = [float(v) for v in values]
    except (TypeError, ValueError):
        return False
    return len(values) == len(current) and all(
        abs(a - b) <= _STAMP_TOLERANCE for a, b in zip(values, current)
    )


def recorded_extraction_status(payload: dict) -> tuple[str, list[str]]:
    """Were this file's STORED features produced by the extraction in force now?

    'legacy'   -- the file records neither feature_scaling nor neutral_defaults
    'match'    -- both recorded, both equal to what extract_features() uses now
    'mismatch' -- anything else, with the differences

    "Now" is whatever scorer.extract_features() reads: the loaded bundle's
    values, or during training the module values train_model has just set.
    Only rows WITHOUT raw telemetry depend on this; rows with raw are
    re-extracted and their stored features are never read.
    """
    recorded_scaling = payload.get("feature_scaling")
    recorded_defaults = payload.get("neutral_defaults")
    if recorded_scaling is None and recorded_defaults is None:
        return "legacy", []

    scaling = scorer.get_feature_scaling()
    defaults = scorer.get_neutral_defaults()
    diffs = []
    for name in scorer.LOG_SCALED_FEATURES:
        current = [float(v) for v in scaling.get(name, scorer.FEATURE_SCALING[name])]
        recorded = (recorded_scaling or {}).get(name)
        if not _close(recorded, current):
            diffs.append(f"feature_scaling.{name}: dosya {recorded}, guncel {current}")
    for name in scorer.NEUTRAL_FEATURES:
        current = float(defaults.get(name, 0.0))
        recorded = (recorded_defaults or {}).get(name)
        if not _close(recorded, [current]):
            diffs.append(f"neutral_defaults.{name}: dosya {recorded}, guncel {current}")
    return ("match" if not diffs else "mismatch"), diffs


def _loud(lines: list[str]) -> None:
    bar = "=" * 66
    print("\n" + bar + "\n" + "\n".join(f" {line}" for line in lines) + "\n" + bar)


def load_real_rows(path: str = REAL_TELEMETRY_PATH) -> dict | None:
    """Every usable labelled real row, in the coordinate system in force NOW.

    This is the answer to the project's oldest weakness: the models were
    trained entirely on personas written by the same author as the detector,
    so their separation was partly self-fulfilling. The browser lab showed
    what that costs -- the same evasive attack scored 88.9 (blocked) in the
    simulator and 36.5 (approved) through real Chromium, because the heaviest
    timing features are inverted between the two distributions.

    The rows carry REAL_TELEMETRY_WEIGHT each, which makes the way they are
    stored matter. The lab used to store only normalised features, frozen to
    the feature_scaling and neutral_defaults of the bundle that happened to be
    serving at capture time: change the simulator, retrain, and every real row
    silently sits in the old coordinate system while outweighing 120 synthetic
    rows. So a row carrying the raw flush is re-extracted here, through the
    same scorer.extract_features() the API calls, and cannot mis-align. A row
    without raw is used only when the file records the extraction that
    produced it and that extraction is still the one in force.

    Returns parallel arrays -- X, y, holdout (bool), from_raw (bool) -- and
    lists scenario, group (the split unit), session (the smoothing unit) and
    order (flush order within a session), or None.
    """
    payload = _read_real_payload(path)
    if payload is None:
        return None
    samples = payload["samples"]
    usable, holdout, incomplete, idle = _structural_split(samples)

    if incomplete:
        print(
            f"  WARNING: {incomplete}/{len(samples)} real rows predate the current "
            "feature set and carry no raw telemetry; skipped. Re-run lab/capture.py."
        )
    if idle:
        print(
            f"  {idle} real rows skipped: raw flush with no timestamped event (idle tab). "
            "/api/analyze neither stores nor scores such a flush."
        )

    keep_stored = True
    stored_only = sum(1 for s in usable if _sample_raw(s) is None)
    if stored_only:
        status, diffs = recorded_extraction_status(payload)
        if status == "legacy":
            _loud([
                f"UYARI: {path}",
                f" {stored_only} gercek satir ham telemetri icermiyor ve dosya, bu",
                " ozellikleri ureten feature_scaling / neutral_defaults degerlerini",
                " kaydetmiyor. Eski format; satirlar DOGRULANAMADAN kullaniliyor.",
                " Simulator veya olcekleme degistiyse bu satirlar yanlis koordinat",
                " sisteminde ve her biri 120 sentetik satir agirliginda.",
                " Cozum: lab/capture.py ile yeniden yakalayin (ham telemetri yazar).",
            ])
        elif status == "mismatch":
            keep_stored = False
            _loud([
                f"UYARI: {path}",
                f" {stored_only} gercek satir ham telemetri icermiyor ve kayitli",
                " cikarim ayarlari guncel olanlarla UYUSMUYOR. Bu satirlar ATLANIYOR;",
                " baska bir olcekte normalize edilmis ozellikler modeli bozar.",
                *[f"   {d}" for d in diffs[:6]],
                " Cozum: lab/capture.py ile yeniden yakalayin (ham telemetri yazar).",
            ])

    X, y, holdout_flags, from_raw = [], [], [], []
    scenario, group, session, order = [], [], [], []
    for position, sample in enumerate(usable):
        raw = _sample_raw(sample)
        if raw is None:
            if not keep_stored:
                continue
            features = sample["features"]
        else:
            features = scorer.extract_features(raw)
        X.append([float(features[name]) for name in FEATURE_NAMES])
        y.append(int(sample["label"]))
        holdout_flags.append(_group_of(sample) in holdout)
        from_raw.append(raw is not None)
        scenario.append(sample["scenario"])
        group.append(_group_of(sample))
        session.append(_session_key(sample))
        order.append(sample.get("flush_index", position))
    if not X:
        return None

    return {
        "X": np.array(X, dtype=float),
        "y": np.array(y),
        "holdout": np.array(holdout_flags, dtype=bool),
        "from_raw": np.array(from_raw, dtype=bool),
        "scenario": scenario,
        "group": group,
        "session": session,
        "order": order,
    }


def load_real_split(path: str = REAL_TELEMETRY_PATH) -> dict | None:
    """load_real_rows(), split into training rows and held-out rows."""
    rows = load_real_rows(path)
    if rows is None:
        return None
    evaluate = rows["holdout"]
    train = ~evaluate
    if not train.any() or not evaluate.any():
        return None

    def pick(values, mask):
        return [v for v, keep in zip(values, mask) if keep]

    return {
        "X_train": rows["X"][train],
        "y_train": rows["y"][train],
        "X_eval": rows["X"][evaluate],
        "y_eval": rows["y"][evaluate],
        "eval_scenarios": pick(rows["scenario"], evaluate),
        "eval_sessions": pick(rows["session"], evaluate),
        "eval_order": pick(rows["order"], evaluate),
        "raw_rows": int(rows["from_raw"].sum()),
    }


def load_real_telemetry(path: str = REAL_TELEMETRY_PATH):
    """Labelled real-browser telemetry, split by run.

    Returns (X_train, y_train, X_eval, y_eval, eval_scenarios) or None. Kept
    for benchmark.py and the tests; load_real_split() carries the session
    order the conformal calibration needs.
    """
    split = load_real_split(path)
    if split is None:
        return None
    return (
        split["X_train"],
        split["y_train"],
        split["X_eval"],
        split["y_eval"],
        split["eval_scenarios"],
    )


def load_real_raw_for_scaling(path: str = REAL_TELEMETRY_PATH) -> list[dict]:
    """Raw flushes from the TRAINING side of the real split.

    Held-out rows stay out of the scaling pool for the same reason they stay
    out of the forest: a scale fitted to them would make the holdout number
    describe data the pipeline had already looked at.
    """
    payload = _read_real_payload(path)
    if payload is None:
        return []
    usable, holdout, _, _ = _structural_split(payload["samples"])
    return [
        raw
        for raw, sample in ((_sample_raw(s), s) for s in usable)
        if raw is not None and _group_of(sample) not in holdout
    ]


# main.py's ladder blocks at 80. Mirrored rather than imported, as benchmark.py
# does, because importing main requires the deployment secrets.
BLOCK_SCORE = 80.0


def session_level_human_calibration(rf, scaler, X_eval, y_eval, sessions, order) -> list[float]:
    """Held-out human scores on the scale /api/decision compares them against.

    The conformal guard is asked about session.risk_score, which is the
    SMOOTHED score: /api/analyze folds each per-flush forest score into it with
    scorer.smooth_session_score(). Calibrating on per-flush probabilities put
    the guard's reference sample on a different scale from the value it
    judges: the median holds a level for several flushes after it has passed,
    and the level-shift rule lets some single spikes through and not others,
    so the two distributions differ in both directions and a p-value read off
    the per-flush one is not the p-value the guard claims to compute.

    So each held-out human session is replayed in flush order exactly as the
    API scores it, and every smoothed value it passes through is kept: the
    decision can be requested after any flush.
    """
    human = np.flatnonzero(np.asarray(y_eval) == 0)
    if not len(human):
        return []
    proba = rf.predict_proba(scaler.transform(np.asarray(X_eval)[human]))[:, 1]

    by_session: dict[str, list[tuple]] = {}
    for idx, p in zip(human, proba):
        # Rounded exactly as compute_risk rounds the per-flush score it stores.
        by_session.setdefault(sessions[idx], []).append((order[idx], round(100.0 * float(p), 1)))

    calibration = []
    for key in sorted(by_session):
        per_flush: list[float] = []
        for _, score in sorted(by_session[key], key=lambda item: item[0]):
            calibration.append(scorer.smooth_session_score(per_flush, score))
            per_flush.append(score)
    return calibration


def report_real_holdout(rf, scaler, X_eval, y_eval, scenarios):
    """Accuracy on held-out REAL browser runs, broken down by scenario.

    The aggregate number hides the only asymmetry that matters: blocking a
    legitimate keyboard-only user costs a sale and a support call, while
    missing one bot costs one fraudulent attempt.
    """
    if len(y_eval) == 0:
        return
    proba = rf.predict_proba(scaler.transform(X_eval))[:, 1]
    print("\nHeld-out REAL browser runs (never seen in training):")
    print(f"  {'scenario':<20}{'n':>5}{'mean p(bot)':>14}{'flagged >=0.5':>15}")
    for name in sorted(set(scenarios)):
        idx = [i for i, sc in enumerate(scenarios) if sc == name]
        p = proba[idx]
        flagged = 100.0 * float((p >= 0.5).mean())
        print(f"  {name:<20}{len(idx):>5}{p.mean():>14.3f}{flagged:>14.0f}%")
    human = proba[y_eval == 0]
    bot = proba[y_eval == 1]
    if len(human) and len(bot):
        fpr = 100.0 * float((human >= 0.5).mean())
        recall = 100.0 * float((bot >= 0.5).mean())
        print(f"  overall: false positives {fpr:.1f}%, bot recall {recall:.1f}%")


# Fewest values a pool needs before its percentiles set a scale. The synthetic
# pool has always needed this many; real values need the same before they may
# move an endpoint, or one odd run could set the scale for everything.
MIN_SCALING_VALUES = 50


def _weighted_percentile(values: np.ndarray, weights: np.ndarray, q: float) -> float:
    """Percentile of a weighted sample (midpoint CDF, linear interpolation)."""
    order = np.argsort(values, kind="mergesort")
    v, w = values[order], weights[order]
    cdf = (np.cumsum(w) - 0.5 * w) / w.sum()
    return float(np.interp(q / 100.0, cdf, v))


def compute_feature_scaling(n_sessions: int = SCALING_SESSIONS, real_raw: list[dict] | None = None) -> dict:
    """Measures where each heavy-tailed feature actually lives, and returns the
    log10 endpoints used to map it onto 0..1.

    This exists because the previous hand-picked divisors were wrong by orders
    of magnitude, and clipping hid it: acceleration variance divided by 2.2e-6
    put every jittered pointer path -- human or bot -- at exactly 1.000, so the
    feature answered "does the pointer wobble?" and nothing else. Two pixels of
    gaussian noise was enough to flip it.

    Percentiles rather than min/max, so one freak session cannot set the scale
    for everything else. Deliberately spans BOTH classes: the useful resolution
    is in the range between robotic and human, and cutting the scale at the
    human 1st percentile would flatten every bot to zero and throw that away.

    Runs on RAW values, so unlike the neutral fallbacks it needs no fixed-point
    iteration -- nothing here depends on its own output.

    `real_raw` are raw real-browser flushes (load_real_raw_for_scaling). A
    scale fitted to the simulator alone clipped real traffic: in the lab
    capture ivme_degisimi sat at exactly 1.0 in 90 of 234 rows, a value that
    carries one bit. Real values therefore join the pool, each weighted so the
    real values of a feature carry the SAME total mass as its synthetic
    values -- the 50/50 blend REAL_TELEMETRY_WEIGHT gives the forest's own
    training rows. At unit weight a couple of hundred real flushes against
    fifteen thousand synthetic windows are about 1% of the pool, and the 99th
    percentile would not move for them however far out they sit. The weight is
    per feature rather than the fixed 120, because the ratio has to hold
    whatever SCALING_SESSIONS is and however often each feature is measurable.

    The blend can only WIDEN the synthetic range. Narrowing it would clip
    simulator rows that fit today, and a wider range costs a tree nothing:
    splits depend on the ordering of values, which rescaling preserves and
    only clipping destroys.
    """
    samples = {name: [] for name in scorer.LOG_SCALED_FEATURES}
    for _ in range(n_sessions):
        base_t = 1_700_000_000_000 + int(rng.integers(0, 10**9))
        persona = _pick_persona(int(rng.integers(0, 2)))
        for payload in simulate_session_windows(persona, base_t):
            for name, value in scorer.extract_raw(payload).items():
                if name in samples and value is not None and np.isfinite(value):
                    samples[name].append(max(float(value), scorer.RAW_FLOOR))

    real_samples = {name: [] for name in scorer.LOG_SCALED_FEATURES}
    for raw in real_raw or []:
        for name, value in scorer.extract_raw(raw).items():
            if name in real_samples and value is not None and math.isfinite(value):
                real_samples[name].append(max(float(value), scorer.RAW_FLOOR))

    scaling = {}
    for name, values in samples.items():
        if len(values) < MIN_SCALING_VALUES:
            scaling[name] = scorer.FEATURE_SCALING[name]
            print(f"  {name}: only {len(values)} samples, keeping fallback")
            continue
        logs = np.log10(np.asarray(values))
        lo, hi = float(np.percentile(logs, 1)), float(np.percentile(logs, 99))

        real_values = real_samples[name]
        if len(real_values) >= MIN_SCALING_VALUES:
            real_logs = np.log10(np.asarray(real_values))
            pool = np.concatenate([logs, real_logs])
            weights = np.concatenate(
                [np.ones(len(logs)), np.full(len(real_logs), len(logs) / len(real_logs))]
            )
            clipped_before = float(((real_logs < lo) | (real_logs > hi)).mean())
            lo = min(lo, _weighted_percentile(pool, weights, 1))
            hi = max(hi, _weighted_percentile(pool, weights, 99))
            clipped_after = float(((real_logs < lo) | (real_logs > hi)).mean())
            print(
                f"  {name}: {len(real_values)} real values in the pool; real values "
                f"clipped {100 * clipped_before:.0f}% -> {100 * clipped_after:.0f}%"
            )
        elif real_values:
            print(
                f"  {name}: only {len(real_values)} real values "
                f"(< {MIN_SCALING_VALUES}), synthetic range kept"
            )

        if hi - lo < 0.5:  # degenerate spread; widen so the feature stays usable
            mid = (hi + lo) / 2.0
            lo, hi = mid - 0.5, mid + 0.5
        scaling[name] = (round(lo, 3), round(hi, 3))
    return scaling


def converge_neutral_defaults() -> dict:
    """Finds neutral fallbacks that TRAINING AND SERVING BOTH USE.

    This has to be a fixed point, not a single calculation, and the reason is
    worth spelling out. A sparse flush -- no scroll, no mouse -- takes the
    fallback value for those features, so every such session in the training
    set sits at exactly the same coordinate. Thousands of identical points
    make a dense atom, and the forest learns sharp splits right next to it.
    Compute a new fallback from that dataset and ship it, and inference now
    places sparse sessions at a coordinate the training data never contained,
    on the far side of those splits. Measured cost of getting this wrong:
    RandomForest scored a headless bot at p(fraud) = 0.000.

    So: run a small pilot, derive the midpoints, feed them back into feature
    extraction, and repeat. The values that come out are the values the real
    dataset is then generated with, and they are what gets stored in the
    bundle -- one consistent set everywhere.
    """
    defaults = dict(scorer.NEUTRAL_DEFAULTS)
    for pass_index in range(PILOT_PASSES):
        X, _, y = generate_synthetic_dataset(PILOT_SESSIONS)
        defaults = compute_neutral_defaults(X, y)
        # extract_features() reads this dict whenever no bundle is loaded,
        # which is the case for the whole of training.
        scorer.NEUTRAL_DEFAULTS.update(defaults)
        print(f"  pilot {pass_index + 1}/{PILOT_PASSES}: {defaults}")
    return defaults


def compute_neutral_defaults(X: np.ndarray, y: np.ndarray) -> dict:
    """Midpoint between the human and bot means of each fallback feature.

    scorer.py uses these when a flush carries too little raw signal to compute
    a feature at all. Deriving them here rather than hand-writing them in
    scorer.py is the point: they track the training distribution automatically
    instead of drifting stale the next time a persona is retuned.
    """
    defaults = {}
    for name in scorer.NEUTRAL_FEATURES:
        idx = FEATURE_NAMES.index(name)
        human_mean = float(X[y == 0, idx].mean())
        bot_mean = float(X[y == 1, idx].mean())
        defaults[name] = round(float(np.clip((human_mean + bot_mean) / 2.0, 0.0, 1.0)), 3)
    return defaults


def train_tabular_models(X_train, y_train, X_test, y_test, sample_weight=None):
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # max_features caps how many of the 6 features each split can consider.
    # Left at sklearn's default ("sqrt" -> 2 of 6), a single near-perfectly
    # separable feature still gets picked at most splits it's eligible for,
    # so the forest ends up overwhelmingly dependent on whichever feature is
    # cleanest in the training data -- a single incidental miss on that one
    # feature at inference time then overrides all other signal. Allowing
    # more features per split forces trees to also learn from the rest.
    # min_samples_leaf forces each leaf to generalize over multiple samples
    # instead of memorizing narrow, overfit decision "islands" -- a gentler
    # smoothing than an earlier attempt at max_depth=8 + min_samples_leaf=15,
    # which over-corrected and hurt bot recall. This is a lighter touch.
    rf = RandomForestClassifier(
        n_estimators=200,
        max_depth=12,
        max_features=4,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1,
    )
    rf.fit(X_train_scaled, y_train, sample_weight=sample_weight)

    y_pred = rf.predict(X_test_scaled)
    rf_acc = accuracy_score(y_test, y_pred)
    print(f"RandomForest test accuracy: {rf_acc:.4f}")
    print("\nClassification Report (RandomForest):")
    print(classification_report(y_test, y_pred, target_names=["Gerçek Kullanıcı", "Bot"], digits=4))

    # Isolation Forest trains only on human (non-fraud) behavior to flag anomalies
    human_only = X_train_scaled[y_train == 0]
    iso_forest = IsolationForest(
        n_estimators=200, contamination=0.05, random_state=42, n_jobs=-1
    )
    iso_forest.fit(human_only)

    return scaler, rf, iso_forest


def train_lstm(seq_train_np, y_train, seq_test_np, y_test, epochs: int = 8, batch_size: int = 256):
    """Trains on the real per-flush sequences from simulate_session_windows().

    Previously this tiled one aggregate row across all ten timesteps and
    added noise, so every "sequence" was ten copies of the same instant and
    the model could not learn anything time-shaped -- while still carrying
    30% of the ensemble weight.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    seq_train = torch.tensor(seq_train_np, dtype=torch.float32)
    seq_test = torch.tensor(seq_test_np, dtype=torch.float32)
    y_train_t = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
    y_test_t = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

    model = BehaviorLSTM().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    criterion = nn.BCELoss()

    n_train = seq_train.shape[0]
    for epoch in range(epochs):
        model.train()
        permutation = torch.randperm(n_train)
        epoch_loss = 0.0
        for i in range(0, n_train, batch_size):
            idx = permutation[i : i + batch_size]
            batch_x = seq_train[idx].to(device)
            batch_y = y_train_t[idx].to(device)

            optimizer.zero_grad()
            preds = model(batch_x)
            loss = criterion(preds, batch_y)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * batch_x.size(0)

        model.eval()
        with torch.no_grad():
            test_preds = model(seq_test.to(device))
            test_acc = ((test_preds > 0.5).float().cpu() == y_test_t).float().mean().item()
        print(f"LSTM epoch {epoch + 1}/{epochs} - loss: {epoch_loss / n_train:.4f} - test_acc: {test_acc:.4f}")

    return model


def main():
    # sklearn's classification_report carries Turkish class names, and a
    # Windows console defaults to cp1252, where "ı" is unencodable -- the
    # run died on a print() after the forest was already trained.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):
        pass

    print("Measuring raw feature distributions for normalization...")
    # Order matters here. The scale must exist before any feature is
    # extracted, and the real rows' features are extracted from raw with that
    # scale -- so their RAW values are read first, and their features only
    # after the scale and the neutral fallbacks are final (load_real_split
    # below).
    real_scaling_raw = load_real_raw_for_scaling()
    if real_scaling_raw:
        print(f"  {len(real_scaling_raw)} training-side real flushes carry raw telemetry")
    feature_scaling = compute_feature_scaling(real_raw=real_scaling_raw)
    # extract_features() reads this whenever no bundle is loaded, which is the
    # case for the whole of training, so the dataset below is generated with
    # exactly the scaling that will be stored and served.
    scorer.FEATURE_SCALING.update(feature_scaling)
    print(f"Feature scaling (log10 range): {feature_scaling}")

    print("Converging neutral fallback values...")
    neutral_defaults = converge_neutral_defaults()

    print(
        f"Generating {N_SESSIONS} synthetic sessions "
        f"({SEQUENCE_LENGTH} flushes each, "
        f"{SEQUENCE_LENGTH * FLUSH_INTERVAL_MS / 1000:.0f}s per session)..."
    )
    X, sequences, y = generate_synthetic_dataset()

    # Split on indices so the aggregate rows and their sequences stay aligned:
    # sequences[i] must remain the history whose last timestep is X[i].
    idx_train, idx_test = train_test_split(
        np.arange(len(y)), test_size=0.2, random_state=42, stratify=y
    )
    X_train, X_test = X[idx_train], X[idx_test]
    y_train, y_test = y[idx_train], y[idx_test]
    seq_train, seq_test = sequences[idx_train], sequences[idx_test]

    print(f"Neutral defaults in force: {neutral_defaults}")

    # Loaded only now: rows carrying raw telemetry are re-extracted with the
    # scale and fallbacks settled above.
    real = load_real_split()
    if real is None:
        print(
            "\n" + "==================================================================" + "\n"
            f" UYARI: {REAL_TELEMETRY_PATH} bulunamadi.\n"
            " Model YALNIZCA SENTETIK VERIYLE egitiliyor. Simulator zamanlama"
            " ozelliklerinde yanlis isareti ogretir: ayni kacamak saldiri\n"
            " simulasyonda 88.9 (bloklandi), gercek Chromium uzerinden 36.5\n"
            " (onaylandi) aldi. Boyle egitilen model, yayinlanan degerlendirme"
            " sayilarinin tarif ettigi model DEGILDIR.\n"
            " Cozum: lab/capture.py calistirin veya REAL_TELEMETRY_PATH ayarlayin."
            + "\n" + "=================================================================="
        )
        X_fit, y_fit, weights = X_train, y_train, None
    else:
        X_real, y_real = real["X_train"], real["y_train"]
        X_real_eval, y_real_eval = real["X_eval"], real["y_eval"]
        real_eval_scenarios = real["eval_scenarios"]
        print(
            f"\nBlending {len(y_real)} real-browser rows into training "
            f"({len(y_real_eval)} held out by run; "
            f"{real['raw_rows']} re-extracted from raw telemetry)."
        )
        X_fit = np.vstack([X_train, X_real])
        y_fit = np.concatenate([y_train, y_real])
        weights = np.concatenate(
            [np.ones(len(y_train)), np.full(len(y_real), REAL_TELEMETRY_WEIGHT)]
        )

    print("Training RandomForest + IsolationForest...")
    scaler, rf, iso_forest = train_tabular_models(X_fit, y_fit, X_test, y_test, weights)
    human_calibration = []
    if real is not None:
        report_real_holdout(rf, scaler, X_real_eval, y_real_eval, real_eval_scenarios)
        # Scores the finished model gives to held-out REAL human sessions.
        # scorer's conformal guard uses these to refuse blocking on a score
        # that is unremarkable for a legitimate user. Held out by run, so the
        # calibration is not measuring sessions the forest was fitted on, and
        # SMOOTHED per session, because the guard judges session.risk_score.
        human_calibration = session_level_human_calibration(
            rf, scaler, X_real_eval, y_real_eval, real["eval_sessions"], real["eval_order"]
        )
        if human_calibration:
            sessions = len({s for s, label in zip(real["eval_sessions"], y_real_eval) if label == 0})
            floor = 1.0 / (len(human_calibration) + 1.0)
            p_at_block = scorer.conformal_p_value(BLOCK_SCORE, human_calibration)
            print(
                f"Conformal calibration: n={len(human_calibration)} session-level smoothed "
                f"scores from {sessions} held-out human sessions, max {max(human_calibration):.1f}, "
                f"smallest achievable p-value {floor:.3f} (guard alpha {scorer.CONFORMAL_ALPHA})."
            )
            print(
                f"  p-value of a {BLOCK_SCORE:.0f} score: {p_at_block:.3f} -> the guard "
                + (
                    f"CAN soften a block at {BLOCK_SCORE:.0f}."
                    if p_at_block > scorer.CONFORMAL_ALPHA
                    else f"cannot soften any block (every blocked score is >= {BLOCK_SCORE:.0f})."
                )
            )
            if floor > scorer.CONFORMAL_ALPHA:
                print(
                    "  NOTE: too few calibration humans to assert that alpha, so the guard "
                    "will soften every block. Capture more real sessions before relying on it."
                )

    lstm = None
    if TRAIN_LSTM:
        print("TRAIN_LSTM=1: training the LSTM for re-measurement (not served)...")
        lstm = train_lstm(seq_train, y_train, seq_test, y_test)

    joblib.dump(
        {
            "scaler": scaler,
            "rf": rf,
            "iso_forest": iso_forest,
            "feature_names": FEATURE_NAMES,
            # Read back by scorer.ModelBundle, which refuses to load a pickle
            # written by a different scikit-learn rather than scoring with it
            # and hoping.
            "sklearn_version": sklearn.__version__,
            # Where each heavy-tailed feature actually lives, measured rather
            # than guessed. Serving must normalize exactly as training did.
            "feature_scaling": feature_scaling,
            "neutral_defaults": neutral_defaults,
            "human_calibration": human_calibration,
        },
        scorer.MODEL_PATH,
    )
    print(f"Saved {os.path.basename(scorer.MODEL_PATH)}")
    if lstm is not None:
        torch.save(lstm.state_dict(), scorer.LSTM_PATH)
        print(f"Saved {os.path.basename(scorer.LSTM_PATH)} (re-measurement only)")


if __name__ == "__main__":
    main()
