"""Generates synthetic human/bot behavior data and trains the DeepCheck models.

Run this before starting the backend:
    python train_model.py

Produces:
    model.pkl      -- joblib bundle: {scaler, rf, iso_forest, feature_names}
    lstm_model.pt  -- PyTorch state_dict for BehaviorLSTM

Training data is generated by simulating *raw* behavioral sessions (mouse
trajectories, click timings, scroll events, keydown timestamps) for human and
bot personas, then running them through the same `scorer.extract_features()`
used at inference time -- not by hand-picking numbers directly in [0, 1] for
each feature. This closes the gap that caused ivme_degisimi to previously be
generated in a completely different numeric range than what the real
extraction formula could ever produce (see scorer.py's
ACCELERATION_VARIANCE_DIVISOR comment). Any future change to a feature
formula automatically flows into training data too, since both paths run the
same code.
"""

import joblib
import numpy as np
import torch
import torch.nn as nn
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from lstm_model import FEATURE_NAMES, NUM_FEATURES, SEQUENCE_LENGTH, BehaviorLSTM
from scorer import extract_features

N_ROWS = 50_000
HESITATION_THRESHOLD_MS = 400  # must match sdk/deepcheck.js's HESITATION_THRESHOLD_MS

# Fraction of each class simulated as the "other" persona -- sophisticated
# bots that mimic human timing (bot_sophisticated), and rushed/efficient
# humans that look more robotic (human_rushed). Without this, the two classes
# would be cleanly separable, which is a modeling smell, not a real result.
CONTAMINATION_RATE = 0.10

rng = np.random.default_rng(42)


def _hesitation_intervals(event_times: list[int], flush_checkpoint: int | None = None) -> list[int]:
    """Mirrors sdk/deepcheck.js's recordHesitation() + its flush-time idle
    check: gaps >= threshold between consecutive tracked events count, AND
    if the flush happens while the session has gone quiet since the last
    event, that trailing silence counts too. Without the trailing check, a
    burst of activity followed by pure idle time until the window closes was
    invisible to hesitation tracking on both the SDK and training-data
    sides -- fixing only one would reintroduce a train/serve mismatch."""
    ts = sorted(event_times)
    gaps = [b - a for a, b in zip(ts, ts[1:]) if (b - a) >= HESITATION_THRESHOLD_MS]
    if flush_checkpoint is not None and ts:
        trailing_gap = flush_checkpoint - ts[-1]
        if trailing_gap >= HESITATION_THRESHOLD_MS:
            gaps.append(trailing_gap)
    return gaps


def _simulate_session(persona: str, base_t: int) -> dict:
    """Simulates a raw ~10s rolling-window SDK payload for one persona.

    Personas:
      human              -- natural mouse jitter, varied typing rhythm, occasional pauses/scroll
      human_rushed       -- genuine human but fast/efficient, minimal hesitation (contamination)
      bot                -- naive/headless: no mouse, instant scripted clicks+keys, zero pauses
      bot_sophisticated  -- mimics human but too smooth/regular (contamination)
    """
    mouse_trajectory: list[dict] = []
    click_timing: list[dict] = []
    scroll_events: list[dict] = []
    key_events: list[dict] = []
    focus_changes: list[float] = []
    all_times: list[int] = []

    t = base_t

    if persona == "bot":
        # Two bot sub-variants: fully headless scripts (form.value set directly,
        # no mouse/scroll simulation at all) and scripted-with-motion bots
        # (Selenium/Puppeteer-style scripts that DO dispatch synthetic
        # mousemove/scroll, but linearly/robotically -- rapid uniform
        # clicking, constant-velocity mouse, perfectly-spaced scroll). Without
        # this second variant, the model only ever learns "zero signal at all
        # = bot" and never learns what a robotic-but-present signal looks
        # like, so a bot that does simulate motion goes undetected.
        headless = rng.random() < 0.5

        # Sometimes zero clicks entirely (a script that calls form.submit()
        # or dispatches keydown-only input events, never a click at all).
        # Without this, tiklama_yogunlugu==0.0 never appears in training for
        # ANY persona (every persona's minimum was >=1 click), so the model
        # had never seen that value and extrapolated it arbitrarily at
        # inference time -- e.g. a real Tab-only keyboard session.
        if rng.random() < 0.15:
            n_clicks = 0
        else:
            n_clicks = int(rng.integers(1, 3)) if headless else int(rng.integers(4, 10))
        click_gap = (
            (lambda: int(rng.integers(1, 5)))
            if headless
            else (lambda: max(150 + int(rng.normal(0, 8)), 1))
        )
        for _ in range(n_clicks):
            click_timing.append({"x": 300, "y": 200, "t": t})
            all_times.append(t)
            t += click_gap()

        # Real automation isn't always perfectly instant end-to-end: page
        # loads, API round trips, explicit sleep()s between scripted steps,
        # or basic rate-limit evasion delays are common. Without this, EVERY
        # bot sample has hesitation_intervals=[] (a gap never reaches the
        # 400ms threshold), which trains the model to treat "hesitation
        # exactly at the neutral fallback" as an almost-perfect bot
        # fingerprint -- a single incidental pause at inference time then
        # flips the whole verdict despite every other signal staying bot-like.
        if rng.random() < 0.30:
            t += int(rng.uniform(400, 1100))

        n_keys = int(rng.integers(0, 20))
        key_gap = (
            (lambda: int(rng.integers(1, 5)))
            if headless
            else (lambda: max(3 + int(rng.normal(0, 1)), 1))
        )
        for _ in range(n_keys):
            key_events.append({"t": t})
            all_times.append(t)
            t += key_gap()

        if not headless:
            # Small jitter (much smaller than human's) instead of a
            # mathematically perfect constant: real scripted mousemove/scroll
            # dispatch still has some OS/rendering timing noise. Without
            # this, ivme_degisimi/scroll_hizi_varyansi hit an exact-zero
            # constant for every such bot sample, which is the same
            # single-feature-fingerprint brittleness as the hesitation issue,
            # just on a different feature.
            n_points = int(rng.integers(10, 20))
            x, y = 100.0, 100.0
            tm = base_t
            for _ in range(n_points):
                x += 5.0 + rng.normal(0, 3.0)
                y += 2.0 + rng.normal(0, 2.2)
                tm += max(80 + int(rng.normal(0, 10)), 1)
                mouse_trajectory.append({"x": x, "y": y, "t": tm})
                all_times.append(tm)

            n_scroll = int(rng.integers(4, 8))
            ts = base_t
            for i in range(1, n_scroll + 1):
                ts += max(90 + int(rng.normal(0, 6)), 1)
                scroll_events.append({"scrollY": 50 * i, "t": ts})
                all_times.append(ts)

    elif persona == "bot_sophisticated":
        n_points = int(rng.integers(15, 30))
        x, y = 200.0, 200.0
        vx, vy = rng.uniform(2, 5), rng.uniform(1, 3)  # near-constant velocity, minimal jitter
        for _ in range(n_points):
            # More jitter than the plain "bot" variant -- this persona is
            # meant to be the hard-to-detect, human-mimicking bot, so its
            # acceleration profile should land closer to human territory.
            x += vx * 10 + rng.normal(0, 2.5)
            y += vy * 10 + rng.normal(0, 1.8)
            t += max(80 + int(rng.normal(0, 7)), 1)  # mostly regular interval
            mouse_trajectory.append({"x": x, "y": y, "t": t})
            all_times.append(t)

        # Same rationale as the "bot" branch above: an occasional realistic
        # pause between phases, so the model can't rely on
        # hesitation_intervals==[] as a near-guaranteed bot fingerprint.
        if rng.random() < 0.30:
            t += int(rng.uniform(400, 1100))

        n_clicks = 0 if rng.random() < 0.15 else int(rng.integers(2, 4))
        for _ in range(n_clicks):
            t += max(500 + int(rng.normal(0, 15)), 1)  # mostly evenly spaced
            click_timing.append({"x": x, "y": y, "t": t})
            all_times.append(t)
        n_keys = int(rng.integers(10, 30))
        for _ in range(n_keys):
            t += max(150 + int(rng.normal(0, 8)), 1)  # mostly too-regular typing interval
            key_events.append({"t": t})
            all_times.append(t)

    elif persona == "human_rushed":
        # NOTE: with tighter dt (faster movement) but similar jitter
        # magnitude to "human", this persona's acceleration variance came out
        # HIGHER than plain "human" (median hit the 1.0 clip ceiling) when
        # first tuned -- dt shrinks the denominator twice (speed, then
        # acceleration), amplifying rather than smoothing. Slightly wider dt
        # and slightly smaller jitter brings it to a believable "efficient
        # but still human" range, below "human" but not off the scale.
        n_points = int(rng.integers(0, 3)) if rng.random() < 0.30 else int(rng.integers(6, 15))
        x, y = rng.uniform(150, 250), rng.uniform(150, 250)
        for _ in range(n_points):
            x += rng.normal(6, 4)
            y += rng.normal(4, 3)
            t += int(rng.uniform(60, 120))
            mouse_trajectory.append({"x": x, "y": y, "t": t})
            all_times.append(t)
        # NOTE: this used to be uniform(150, 400) -- numpy's upper bound is
        # exclusive, so this could NEVER reach HESITATION_THRESHOLD_MS (400),
        # meaning 100% of human_rushed samples got hesitation_intervals=[]
        # (the same "always-exactly-neutral" bug as the bot personas, just
        # discovered on the human side). Widened so some click gaps naturally
        # cross the threshold, like a real (just efficient) human would.
        # Floor of 1 (not 2): a headless bot can also have just 1-2 clicks,
        # so requiring >=2 for every human sample meant "exactly 1 click"
        # was only ever seen from bots in training, wrongly making a single
        # click read as bot-like even for an early-session human snapshot.
        # Also sometimes zero -- a keyboard-only (Tab navigation) user, real
        # and legitimate, never fires a single click event.
        n_clicks = 0 if rng.random() < 0.15 else int(rng.integers(1, 5))
        for _ in range(n_clicks):
            t += int(rng.uniform(150, 650))
            click_timing.append({"x": x, "y": y, "t": t})
            all_times.append(t)
        n_keys = int(rng.integers(10, 35))
        for _ in range(n_keys):
            t += int(rng.uniform(60, 150))
            key_events.append({"t": t})
            all_times.append(t)
        if rng.random() < 0.15:
            t += int(rng.uniform(50, 200))
            scroll_events.append({"scrollY": int(rng.uniform(50, 300)), "t": t})
            all_times.append(t)

    else:  # "human"
        # Real users often fill a form mostly by typing, with little to no
        # mouse movement in a given window -- the SDK simply has nothing to
        # report there. Without ANY human training examples that have sparse
        # mouse data, the model only ever sees that pattern from headless
        # bots (which always have zero mouse points) and learns "no mouse
        # data" as an almost-deterministic bot signature -- no neutral
        # fallback constant can fix that after the fact, since the model
        # keys off having never seen a human example at that value.
        mostly_typing = rng.random() < 0.30
        n_points = int(rng.integers(0, 3)) if mostly_typing else int(rng.integers(10, 40))
        x, y = rng.uniform(150, 250), rng.uniform(150, 250)
        for _ in range(n_points):
            x += rng.normal(6, 6)
            y += rng.normal(4, 5)
            t += int(rng.uniform(50, 150))
            mouse_trajectory.append({"x": x, "y": y, "t": t})
            all_times.append(t)
            if rng.random() < 0.05:  # natural pause while moving the mouse
                t += int(rng.uniform(400, 1200))
        # See note in human_rushed above; also sometimes zero (keyboard-only
        # Tab navigation is a real, legitimate human interaction pattern).
        n_clicks = 0 if rng.random() < 0.15 else int(rng.integers(1, 5))
        for _ in range(n_clicks):
            t += int(rng.uniform(300, 900))  # natural pause before clicking
            click_timing.append({"x": x, "y": y, "t": t})
            all_times.append(t)
        n_keys = int(rng.integers(15, 50))
        for _ in range(n_keys):
            t += int(rng.lognormal(mean=5.0, sigma=0.5))  # ~100-350ms, occasional longer pause
            key_events.append({"t": t})
            all_times.append(t)
        if rng.random() < 0.35:
            sy = 0
            for _ in range(int(rng.integers(2, 6))):
                sy += int(rng.uniform(40, 150))
                t += int(rng.uniform(60, 180))
                scroll_events.append({"scrollY": sy, "t": t})
                all_times.append(t)
        if rng.random() < 0.15:
            focus_changes.append(t + int(rng.uniform(500, 3000)))

    # Simulate the flush boundary itself: activity is often followed by real
    # idle time before the window closes (e.g. a fast burst of typing, then
    # nothing until the next flush fires). See _hesitation_intervals().
    flush_checkpoint = t
    if rng.random() < 0.40:
        flush_checkpoint = t + int(rng.uniform(400, 2000))

    return {
        "mouse_trajectory": mouse_trajectory,
        "click_timing": click_timing,
        "scroll_events": scroll_events,
        "hesitation_intervals": _hesitation_intervals(all_times, flush_checkpoint),
        "focus_changes": focus_changes,
        "key_events": key_events,
    }


def generate_synthetic_dataset(n_rows: int = N_ROWS):
    is_bot = rng.integers(0, 2, size=n_rows)
    X = np.empty((n_rows, len(FEATURE_NAMES)))

    for i in range(n_rows):
        base_t = 1_700_000_000_000 + int(rng.integers(0, 10**9))
        if is_bot[i]:
            persona = "bot_sophisticated" if rng.random() < CONTAMINATION_RATE else "bot"
        else:
            persona = "human_rushed" if rng.random() < CONTAMINATION_RATE else "human"
        raw = _simulate_session(persona, base_t)
        features = extract_features(raw)
        X[i] = [features[name] for name in FEATURE_NAMES]

    y = is_bot
    return X, y


def build_sequences(X: np.ndarray) -> np.ndarray:
    """Tiles each aggregate feature row across SEQUENCE_LENGTH timesteps with
    small per-step jitter, simulating a rolling 10s behavior window."""
    n = X.shape[0]
    noise = rng.normal(0, 0.02, size=(n, SEQUENCE_LENGTH, NUM_FEATURES))
    seq = np.repeat(X[:, None, :], SEQUENCE_LENGTH, axis=1) + noise
    return np.clip(seq, 0.0, 1.0)


def train_tabular_models(X_train, y_train, X_test, y_test):
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # max_features caps how many of the 6 features each split can consider.
    # Left at sklearn's default ("sqrt" -> 2 of 6), a single near-perfectly
    # separable feature still gets picked at most splits it's eligible for,
    # so the forest ends up overwhelmingly dependent on whichever feature is
    # cleanest in the training data -- a single incidental miss on that one
    # feature at inference time then overrides all other signal. Allowing
    # more features per split forces trees to also learn from the rest.
    # min_samples_leaf forces each leaf to generalize over multiple samples
    # instead of memorizing narrow, overfit decision "islands" -- a gentler
    # smoothing than an earlier attempt at max_depth=8 + min_samples_leaf=15,
    # which over-corrected and hurt bot recall. This is a lighter touch.
    rf = RandomForestClassifier(
        n_estimators=200,
        max_depth=12,
        max_features=4,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1,
    )
    rf.fit(X_train_scaled, y_train)

    y_pred = rf.predict(X_test_scaled)
    rf_acc = accuracy_score(y_test, y_pred)
    print(f"RandomForest test accuracy: {rf_acc:.4f}")
    print("\nClassification Report (RandomForest):")
    print(classification_report(y_test, y_pred, target_names=["Gerçek Kullanıcı", "Bot"], digits=4))

    # Isolation Forest trains only on human (non-fraud) behavior to flag anomalies
    human_only = X_train_scaled[y_train == 0]
    iso_forest = IsolationForest(
        n_estimators=200, contamination=0.05, random_state=42, n_jobs=-1
    )
    iso_forest.fit(human_only)

    return scaler, rf, iso_forest


def train_lstm(X_train, y_train, X_test, y_test, epochs: int = 8, batch_size: int = 256):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    seq_train = torch.tensor(build_sequences(X_train), dtype=torch.float32)
    seq_test = torch.tensor(build_sequences(X_test), dtype=torch.float32)
    y_train_t = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
    y_test_t = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

    model = BehaviorLSTM().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    criterion = nn.BCELoss()

    n_train = seq_train.shape[0]
    for epoch in range(epochs):
        model.train()
        permutation = torch.randperm(n_train)
        epoch_loss = 0.0
        for i in range(0, n_train, batch_size):
            idx = permutation[i : i + batch_size]
            batch_x = seq_train[idx].to(device)
            batch_y = y_train_t[idx].to(device)

            optimizer.zero_grad()
            preds = model(batch_x)
            loss = criterion(preds, batch_y)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * batch_x.size(0)

        model.eval()
        with torch.no_grad():
            test_preds = model(seq_test.to(device))
            test_acc = ((test_preds > 0.5).float().cpu() == y_test_t).float().mean().item()
        print(f"LSTM epoch {epoch + 1}/{epochs} - loss: {epoch_loss / n_train:.4f} - test_acc: {test_acc:.4f}")

    return model


def main():
    print(f"Generating {N_ROWS} synthetic behavior rows...")
    X, y = generate_synthetic_dataset()
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    print("Training RandomForest + IsolationForest...")
    scaler, rf, iso_forest = train_tabular_models(X_train, y_train, X_test, y_test)

    print("Training LSTM...")
    lstm = train_lstm(X_train, y_train, X_test, y_test)

    joblib.dump(
        {
            "scaler": scaler,
            "rf": rf,
            "iso_forest": iso_forest,
            "feature_names": FEATURE_NAMES,
        },
        "model.pkl",
    )
    torch.save(lstm.state_dict(), "lstm_model.pt")
    print("Saved model.pkl and lstm_model.pt")


if __name__ == "__main__":
    main()
